@ECHO OFF
CD %~dp0
copy PacDrive32.dll "..\..\dlls\"
copy PacDrive32.lib "..\..\dlls\"
copy PacDrive32.dll "..\..\C#\bin\Debug\"
copy PacDrive32.dll "..\..\VB.NET\bin\Debug\"
copy PacDrive32.dll "..\..\VB6\"
copy PacDrive32.dll "..\..\Delphi\"
copy PacDrive32.dll "..\..\C++\Release"
copy PacDrive32.lib "..\..\C++\"
copy PacDrive64.dll "..\..\dlls\"
copy PacDrive64.lib "..\..\dlls\"
copy PacDrive64.dll "..\..\C#\bin\Debug\"
copy PacDrive64.dll "..\..\VB.NET\bin\Debug\"
copy PacDrive64.dll "..\..\VB6\"
copy PacDrive64.dll "..\..\Delphi\"
copy PacDrive64.dll "..\..\C++\Release"
copy PacDrive64.lib "..\..\C++\"
copy ..\PacDrive.h "..\..\C++"